# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'PizzaSquare/'
  project: 'PizzaSquare/PizzaSquare.Web/'
  test: 'PizzaSquare/PizzaSquare.Test'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud connection 1'
    organization: '$(SonarOrganization)'
    scannerMode: 'MSBuild'
    projectKey: '$(SonarProjectKey)'
    projectName: '$(SonarProjectName)'
    extraProperties: 
      sonar.cs.opencover.reportPaths="$(Build.ArtifactStagingDirectory)/coverage/*"
      sonar.cs.vstest.reportPaths="$(Build.ArtifactStagingDirectory)/test/*.trx"
      sonar.exclusions=**/wwwroot/lib/**/*

# dotnet build
- script: 
    dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(solution)
  displayName: 'dotnet build $(buildConfiguration)'

# dotnet test
- script: dotnet test
    --configuration $(buildConfiguration)
    --logger trx
    --no-build
    --results-directory $(Build.ArtifactStagingDirectory)/PizzaSquare.Test/
    /p:CollectCoverage=true
    /p:CoverletOutputFormat=opencover
    /p:CoverletOutput="$(Build.ArtifactStagingDirectory)/coverage/"
  workingDirectory: $(solution)
  displayName: 'dotnet test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(test)'
    workingDirectory: '$(solution)'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
